### PR TITLE
Add Support for Metadata In Folders

### PR DESCRIPTION
**Pull request by cwarden**
Add support for retrieving metadata objects contained within folders:
documents, email templates, reports, and dashboards.

### CODE REVIEW

**Comment by kevinohara80** [comment]
I didn't get much time to check into why, but it's not working for me. I have a document folder in my org called `Example` and a file inside of it called `Logo.png`.

The following commands didn't find any metadata.

```bash
$ dmc retrieve 'src/documents/**/*'
[dmc] using org: nforce (default)
[dmc] matching types
[err] no files found for retrieve
[dmc] [NOT OK]

$ dmc retrieve 'src/documents/*'
[dmc] using org: nforce (default)
[dmc] matching types
[err] no files found for retrieve
[dmc] [NOT OK]
```

When I try to grab all metadata, I actually get an error on retrieving one of my workflows. It looks like it's dropping a null into the folder part of the path somewhere...

```bash
$ dmc retrieve 'src/**/*'
[dmc] using org: nforce (default)
[dmc] matching types
[dmc] * matched type: InstalledPackage
[dmc] * matched type: CustomLabels
[dmc] * matched type: StaticResource
[dmc] * matched type: Scontrol
[dmc] * matched type: AuraDefinitionBundle
[dmc] * matched type: ApexComponent
[dmc] * matched type: ApexPage
[dmc] * matched type: Queue
[dmc] * matched type: ExternalDataSource
[dmc] * matched type: Role
[dmc] * matched type: Group
[dmc] * matched type: CustomObject
[dmc] * matched type: ReportType
[dmc] * matched type: Report
[dmc] * matched type: Dashboard
[dmc] * matched type: AnalyticSnapshot
[dmc] * matched type: Layout
[dmc] * matched type: Document
[dmc] * matched type: CustomPageWebLink
[dmc] * matched type: QuickAction
[dmc] * matched type: FlexiPage
[dmc] * matched type: CustomTab
[dmc] * matched type: CustomApplicationComponent
[dmc] * matched type: CustomApplication
[dmc] * matched type: Letterhead
[dmc] * matched type: EmailTemplate
[dmc] * matched type: Flow
[dmc] * matched type: Workflow
[dmc] * matched type: AssignmentRules
[dmc] * matched type: AutoResponseRules
[dmc] * matched type: EscalationRules
[dmc] * matched type: PostTemplate
[dmc] * matched type: ApprovalProcess
[dmc] * matched type: HomePageComponent
[dmc] * matched type: HomePageLayout
[dmc] * matched type: CustomObjectTranslation
[dmc] * matched type: ApexClass
[dmc] * matched type: ApexTrigger
[dmc] * matched type: Profile
[dmc] * matched type: PermissionSet
[dmc] * matched type: CustomMetadata
[dmc] * matched type: DataCategoryGroup
[dmc] * matched type: RemoteSiteSetting
[dmc] * matched type: AuthProvider
[dmc] * matched type: CustomSite
[dmc] * matched type: ChannelLayout
[dmc] * matched type: LeadSharingRules
[dmc] * matched type: CampaignSharingRules
[dmc] * matched type: CaseSharingRules
[dmc] * matched type: ContactSharingRules
[dmc] * matched type: OpportunitySharingRules
[dmc] * matched type: AccountSharingRules
[dmc] * matched type: CustomObjectSharingRules
[dmc] * matched type: UserSharingRules
[dmc] * matched type: SharingSet
[dmc] * matched type: Community
[dmc] * matched type: CallCenter
[dmc] * matched type: ConnectedApp
[dmc] * matched type: AppMenu
[dmc] * matched type: CustomPermission
[dmc] * matched type: SiteDotCom
[dmc] * matched type: SamlSsoConfig
[dmc] * matched type: CorsWhitelistOrigin
[dmc] * matched type: SynonymDictionary
[dmc] * matched type: Settings
[err] Invalid file found: src/null/Billing__c.workflow
[dmc] [NOT OK]
```

The above command does not have this error on master.

Let me know what you think and I'll take a look too when I get home tonight.

**Comment by cwarden** [comment]
Thanks for testing it out, @kevinohara80.  The `null` when retrieving `src/**/*` definitely looks like a bug.  I'll check it out.

The ability to expand wildcards for folder names would be a nice enhancement, but perhaps could be deferred for a future update.  The code currently requires that the folder be named explicitly like the Metadata API.

Expanding folder names requires a little more thought.  Should it include all folders, Shared, Public, Hidden, and PublicInternal?

**Comment by cwarden** [comment]
I haven't been able to reproduce the bug with retrieving `src/**/*` yet.

```
$ dmc retrieve 'src/**/*'
[dmc] using org: xn (default)
[dmc] matching types
[dmc] * matched type: InstalledPackage
[dmc] * matched type: CustomLabels
[dmc] * matched type: StaticResource
[dmc] * matched type: Scontrol
[dmc] * matched type: AuraDefinitionBundle
[dmc] * matched type: ApexComponent
[dmc] * matched type: ApexPage
[dmc] * matched type: Queue
[dmc] * matched type: ExternalDataSource
[dmc] * matched type: NamedCredential
[dmc] * matched type: Role
[dmc] * matched type: Group
[dmc] * matched type: CustomObject
[dmc] * matched type: ReportType
[dmc] * matched type: Report
[dmc] * matched type: Dashboard
[dmc] * matched type: AnalyticSnapshot
[dmc] * matched type: Layout
[dmc] * matched type: Document
[dmc] * matched type: CustomPageWebLink
[dmc] * matched type: QuickAction
[dmc] * matched type: FlexiPage
[dmc] * matched type: CustomTab
[dmc] * matched type: CustomApplication
[dmc] * matched type: Letterhead
[dmc] * matched type: EmailTemplate
[dmc] * matched type: Flow
[dmc] * matched type: FlowDefinition
[dmc] * matched type: Workflow
[dmc] * matched type: AssignmentRules
[dmc] * matched type: AutoResponseRules
[dmc] * matched type: EscalationRules
[dmc] * matched type: ApprovalProcess
[dmc] * matched type: HomePageComponent
[dmc] * matched type: HomePageLayout
[dmc] * matched type: CustomObjectTranslation
[dmc] * matched type: ApexClass
[dmc] * matched type: ApexTrigger
[dmc] * matched type: Profile
[dmc] * matched type: PermissionSet
[dmc] * matched type: CustomMetadata
[dmc] * matched type: DataCategoryGroup
[dmc] * matched type: RemoteSiteSetting
[dmc] * matched type: MatchingRules
[dmc] * matched type: AuthProvider
[dmc] * matched type: CustomSite
[dmc] * matched type: ChannelLayout
[dmc] * matched type: SharingRules
[dmc] * matched type: Community
[dmc] * matched type: CallCenter
[dmc] * matched type: ConnectedApp
[dmc] * matched type: AppMenu
[dmc] * matched type: CustomPermission
[dmc] * matched type: SiteDotCom
[dmc] * matched type: SamlSsoConfig
[dmc] * matched type: CorsWhitelistOrigin
[dmc] * matched type: ActionLinkGroupTemplate
[dmc] * matched type: PathAssistant
[dmc] * matched type: Settings
[dmc] retrieve status: InProgress
...
[dmc] unzipping to tmp dir: /home/cwarden/.dmc/.tmp
[dmc] extracting zip
[dmc] merging files to src
[dmc] cleaning up temporary files
[dmc] removing tmp directory
```

What `api_version` do you have configured in `dmc_config.json`?

**Comment by kevinohara80** [comment]
@cwarden I would think that we'd want to include all folder types. I'm on v32 in my config.

I remember struggling with the folder issue. IIRC, I started to realize that it was going to take multiple API calls. I think we'll need to generate a list of folders first and then list the metadata for each. I don't think it'd be that hard because there's only an handful of md types that support folders.

**Comment by kevinohara80** [comment]
@cwarden Take a look at #18. This works (I think). It does some recursive listmetadata calls to resolve the folder structure first, then get the contents of each folder.

**Pull request closed without merging**
