### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by zachelrath**
# Summary of Changes

- Addresses #44 
- Upgrades `async` dependency, which has known CVE's.
- Upgrades `handlebars` dependency, which has known CVE's.
- Upgrades `mocha` to fix travis CI build issues
- Upgrades `should`
- Adjusts Travis build to run against active LTS (8.10.x) and current (9.7.x).
- Commit the `package-lock.json` so that (a) NPM installs are faster (b) Github's dependency graph scanning can pick up on dependency vulnerabilities and report them automatically.

### CODE REVIEW

**Comment by zachelrath** [comment]
@kevinohara80 Any thoughts on this?

**Comment by kevinohara80** [comment]
Looks good from my phone ;)

I’ll get this merged tomorrow!

**Comment by zachelrath** [comment]
Thanks Kevin, appreciate it!

**Comment by zachelrath** [comment]
@kevinohara80 Any update on this?

**Comment by kevinohara80** [comment]
Sorry for the delay. Published in 1.5.2

**Pull request merged**
